# Global Infrastructure Services
# Shared across all projects in the monorepo
# 
# Services:
# - Redis (cache, message broker, sessions)
# - MinIO (S3-compatible object storage)
#
# Usage:
#   docker compose -f infra/compose.global.yml up -d

services:
  # Global Redis instance for caching, sessions, and message broker
  redis:
    container_name: monorepo-redis
    image: redis:8.4.0-bookworm
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-devpassword}", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - monorepo_net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-devpassword}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis UI for debugging and monitoring
  redisinsight:
    container_name: monorepo-redisinsight
    image: redis/redisinsight:2.70
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    environment:
      - REDISINSIGHT_HOST_URL=redis://default:${REDIS_PASSWORD:-devpassword}@redis:6379
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:5540 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - monorepo_net

  # Global MinIO instance for object storage (S3-compatible)
  minio:
    container_name: monorepo-minio
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    restart: unless-stopped
    networks:
      - monorepo_net
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-devpassword}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
  minio_data:
    driver: local

networks:
  monorepo_net:
    name: monorepo_net
    driver: bridge
